/*  global constants */
export const INIT_IN_PROCESS_STATUS = 'global/INIT_IN_PROCESS_STATUS';

/*  auth constants */
export const SET_AUTH = 'auth/SET_AUTH';
export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const SET_PERSONAL_INFO = 'auth/SET_PERSONAL_INFO';
export const AUTH_ERROR = 'auth/AUTH_ERROR';
export const AUTH_REQUEST_STATUS = 'auth/AUTH_REQUEST_STATUS';

export const CHANGE_FORM = 'CHANGE_FORM';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CHANGE_OFFER_STEP = 'offerCreate/CHANGE_OFFER_STEP';
export const LOCATION_AUTOCOMPLETE_REQUEST = 'offerCreate/LOCATION_AUTOCOMPLETE_REQUEST';
export const UPDATE_AUTOCOMPLETE_LIST = 'offerCreate/UPDATE_AUTOCOMPLETE_LIST';
export const SET_OFFER_LOCATION = 'offerCreate/SET_OFFER_LOCATION';
export const UPDATE_OFFER_DESCRIPTION = 'offerCreate/UPDATE_OFFER_DESCRIPTION';
export const UPDATE_OFFER_PERSONAL = 'offerCreate/UPDATE_OFFER_PERSONAL';
export const CREATE_OFFER = 'offerCreate/CREATE_OFFER';
export const CLEAR_OFFER_FORM = 'offerCreate/CLEAR_OFFER_FORM';
export const SET_OFFER_ERRORS = 'offerCreate/SET_OFFER_ERRORS';


export const UPDATE_SEARCHING_COUNTRIES_REQUEST = 'search/UPDATE_SEARCHING_COUNTRIES_REQUEST';
export const SET_SEARCHING_COUNTRIES = 'search/SET_SEARCHING_COUNTRIES';
export const SET_SEARCHING_COUNTRY = 'search/SET_SEARCHING_COUNTRY';
export const SET_SEARCHING_CITIES = 'search/SET_SEARCHING_CITIES';
export const SET_SEARCHING_CITY = 'search/SET_SEARCHING_CITY';
export const UPDATE_SEARCH_FORM = 'search/UPDATE_SEARCH_FORM';
export const SET_CITY_COORDINATES = 'search/SET_CITY_COORDINATES';
export const SEARCH_REQUEST = 'search/SEARCH_REQUEST';
export const SET_OFFERS = 'search/SET_OFFERS';
export const SET_SEARCHING_PROCESS_STATUS = 'search/SET_SEARCHING_PROCESS_STATUS';
export const UPDATE_URI_QUERY = 'search/UPDATE_URI_QUERY';
export const START_SEARCH_WITH_QUERY = 'search/START_SEARCH_WITH_QUERY';
export const SET_SEARCH_FORM = 'search/SET_SEARCH_FORM';
export const CHANGE_SEARCH_MAP_STATE = 'search/CHANGE_SEARCH_MAP_STATE';
export const SET_SEARCH_ERROR_OBJECT = 'search/SET_SEARCH_ERROR_OBJECT';
export const CLEAR_SEARCH_PAGE = 'search/CLEAR_SEARCH_PAGE';
export const SET_SELECTED_OFFER_ID = 'search/SET_SELECTED_OFFER_ID';
export const UPDATE_SEARCH_AUTOCOMPLETE_LIST = 'search/UPDATE_SEARCH_AUTOCOMPLETE_LIST';
export const LOCATION_SEARCH_AUTOCOMPLETE_REQUEST = 'search/LOCATION_SEARCH_AUTOCOMPLETE_REQUEST';
export const SET_SEARCH_LOCATION = 'search/SET_SEARCH_LOCATION';
export const SAVE_SEARCH_FILTER_REQUEST = 'search/SAVE_SEARCH_FILTER_REQUEST';

export const CHANGE_FILTER_SHOW_STATUS = 'filter/CHANGE_FILTER_SHOW_STATUS';
export const SET_FILTER_ERROR = 'filter/SET_FILTER_ERROR';
export const CHANGE_SAVE_REQUEST_STATUS = 'filter/CHANGE_SAVE_REQUEST_STATUS';

export const CHANGE_OFFER_PAGE_STATUS = 'offerPage/CHANGE_OFFER_PAGE_STATUS';
export const OFFER_PAGE_REQUEST = 'offerPage/OFFER_PAGE_REQUEST';
export const SET_OFFER_PAGE = 'offerPage/SET_OFFER_PAGE';
export const UPLOAD_OFFER_PHOTOS = 'offerPage/UPLOAD_OFFER_PHOTOS';
export const SET_NEW_OFFER_PHOTOS = 'offerPage/SET_NEW_OFFER_PHOTOS';

