/*  global constants */
export const INIT_IN_PROCESS_STATUS = 'global/INIT_IN_PROCESS_STATUS';

/*  auth constants */
export const SET_AUTH = 'auth/SET_AUTH';
export const REGISTER_REQUEST = 'auth/REGISTER_REQUEST';
export const LOGOUT_REQUEST = 'auth/LOGOUT_REQUEST';
export const LOGIN_REQUEST = 'auth/LOGIN_REQUEST';
export const SET_PERSONAL_INFO = 'auth/SET_PERSONAL_INFO';
export const AUTH_ERROR = 'auth/AUTH_ERROR';
export const AUTH_REQUEST_STATUS = 'auth/AUTH_REQUEST_STATUS';

export const CHANGE_FORM = 'CHANGE_FORM';
export const SENDING_REQUEST = 'SENDING_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const CHANGE_OFFER_STEP = 'offer/CHANGE_OFFER_STEP';
export const LOCATION_AUTOCOMPLETE_REQUEST = 'offer/LOCATION_AUTOCOMPLETE_REQUEST';
export const UPDATE_AUTOCOMPLETE_LIST = 'offer/UPDATE_AUTOCOMPLETE_LIST';
export const SET_OFFER_LOCATION = 'offer/SET_OFFER_LOCATION';
export const UPDATE_OFFER_DESCRIPTION = 'offer/UPDATE_OFFER_DESCRIPTION';
export const UPDATE_OFFER_PERSONAL = 'offer/UPDATE_OFFER_PERSONAL';
export const CREATE_OFFER = 'offer/CREATE_OFFER';
export const CLEAR_OFFER_FORM = 'offer/CLEAR_OFFER_FORM';
export const SET_OFFER_ERRORS = 'offer/SET_OFFER_ERRORS';


export const UPDATE_SEARCHING_COUNTRIES_REQUEST = 'search/UPDATE_SEARCHING_COUNTRIES_REQUEST';
export const SET_SEARCHING_COUNTRIES = 'search/SET_SEARCHING_COUNTRIES';
export const SET_SEARCHING_COUNTRY = 'search/SET_SEARCHING_COUNTRY';
export const SET_SEARCHING_CITIES = 'search/SET_SEARCHING_CITIES';
export const SET_SEARCHING_CITY = 'search/SET_SEARCHING_CITY';
export const UPDATE_SEARCH_FORM = 'search/UPDATE_SEARCH_FORM';
export const SET_CITY_COORDINATES = 'search/SET_CITY_COORDINATES';
export const SEARCH_REQUEST = 'search/SEARCH_REQUEST';
export const SET_OFFERS = 'search/SET_OFFERS';
export const SET_SEARCHING_PROCESS_STATUS = 'search/SET_SEARCHING_PROCESS_STATUS';
export const UPDATE_URI_QUERY = 'search/UPDATE_URI_QUERY';
export const START_SEARCH_WITH_QUERY = 'search/START_SEARCH_WITH_QUERY';
export const SET_SEARCH_FORM = 'search/SET_SEARCH_FORM';
export const CHANGE_SEARCH_MAP_STATE = 'search/CHANGE_SEARCH_MAP_STATE';
export const SET_SEARCH_ERROR_OBJECT = 'search/SET_SEARCH_ERROR_OBJECT';




