export const MINSK_COORDINATES = [53.9, 27.56659];

export const LOCATION_QUERY_THROTTLE_TIMEOUT = 1500;

export const SEARCH_CITY_CENTER_TIMEOUT = 300;
export const UPDATE_SEARCH_CITIES_TIMEOUT = 300;
export const SEARCH_REQUEST_TIMEOUT = 300;
export const SAVE_SEARCH_FILTER_TIMEOUT = 500;
